services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_user_password
      MYSQL_DATABASE: product
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-network

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/product
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product_user_password
      MAP_STORAGE_PATH: /app/maps
    volumes:
      - map_images:/app/maps  # Ensure correct mounting
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  mysql_data:
  map_images:

networks:
  shared-network:
    driver: bridge
