server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: EA_Project

  datasource:
    url: jdbc:mysql://mysql_db:3306/product?createDatabaseIfNotExist=true
    username: product_user
    password: product_user_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Updates schema without dropping existing data
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true  # Show SQL queries in logs

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:/app/maps/
    mvc:
      static-path-pattern: /maps/**

  map:
    storage:
      path: /app/maps

spring.mvc.hiddenmethod.filter.enabled: true
